#' The 'predict' method function of the PLSDA class predicts
#'
#'
#' This method function uses the latent scores, loadings, and weights to calculate the response matrix from an unseen set of data
#'
#' @usage predict(pls2Object,newdata)
#'
#' @param pls2Object pls2 class object generated by PLSDA class constructor
#' @param newdata an unseen set of data from which 'predict' method will calculate its response matrix
#'
#' @details


predict.PLSDA <- function(pls2Object,newdata){

  newdata <- as.matrix(scale(newdata))
  instance <- list()
  if(pls2Object$mode=="classic" || pls2Object$mode=="test" ){

    Bpls <- pls2Object$weights$X%*%solve(t(pls2Object$loadings)%*%pls2Object$weights$X)%*%t(pls2Object$weights$Y)
    pred <- newdata%*%Bpls


    instance$B.hat <- Bpls
    instance$pred <- pred


    class(instance) <- "predict"

    return(instance)
  }else{

    if(pls2Object$mode=="SVD"){

      inv_pw<-inv(t(pls2Object$loadings$X)%*%pls2Object$weights$X)

      R.loadings <- pls2Object$weights$X%*%inv_pw

      Bpls <- R.loadings %*% t(pls2Object$weights$Y)

      pred <- newdata%*%Bpls

      instance$B.hat <- Bpls
      instance$pred <- pred


      class(instance) <- "predict"
      return(instance)
    }else{

      stop("Error with prediction object, check prediction mode.")


    }
  }


}
